config/routes.rb
Rails.application.routes.draw do
  root 'recruitments#index'
  devise_for :campanies, controllers: {
    sessions:      'campanies/sessions',
    password:      'campanies/passwords',
    registrations: 'campanies/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  resources :recruitments do
    resources :applies, only: [:create]
  end
  resources :users, only: [:show]
  get   'users/:id'   =>  'users#show'
  get   'campanies/:id'  =>  'campanies#show'
  post 'gcals/create_event_self' => 'gcals#create_event_self'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/apply.rb
class Apply < ApplicationRecord
  belongs_to :user
  belongs_to :recruitment
  has_many :campany, through: :campany_applies
  has_many :campany_applies
end

app/models/campany.rb
class Campany < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recruitments
  has_many :applies, through: :campany_applies
  has_many :users, through: :applies
  has_many :campany_applies
end

app/models/campany_apply.rb
class CampanyApply < ApplicationRecord
  belongs_to :canpany
  belongs_to :apply
end

app/models/campany_user.rb
class CampanyUser < ApplicationRecord
end

app/models/gcal.rb
class Gcal < ApplicationRecord
  def insert_event(event)   #UserのGmailを受け取るので引数が必要
      email = event[0]
      start_time = DateTime.parse(event[2])
      end_time = DateTime.parse(event[3])

       event_resorces = {
                'summary' => event[1],#fullcalendarのtitle
                'start' => {
                            'dateTime' => start_time
                           },
                'end' =>   {
                            'dateTime' => end_time
                           },
                }
  result = @client.execute(:api_method => @service.events.insert,
                               :parameters => {'calendarId' => email },
                               :body => JSON.dump(event_resorces),
                               :headers => {'Content-Type' =>   'application/json'})
  end
end

app/models/job.rb
class Job < ApplicationRecord
  has_many :recruitments
end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  belongs_to :campany
  belongs_to :user
  has_many :users, through: :applies

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  belongs_to :recruitments
  has_many :recruitments, through: :applies
  has_many :applies
  has_many :campanies, through: :applies
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :campany_name, :user_name])
  end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  def create
    @apply = Apply.create(recruitment_id: params[:recruitment_id], user_id: current_user.id, campany_id: params[:campany_id], user_name: current_user.user_name )
    redirect_to root_path
  end

  private
  def apply_params
    params.permit(:recruitment_id, :campany_id )
  end

end

app/controllers/campanies/sessions_controller.rb
class Campanies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/campanies/unlocks_controller.rb
class Campanies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/campanies_controller.rb
class CampaniesController < ApplicationController

  def show
    @applies = Apply.where(recruitment_id: current_campany.recruitments)
  end



  private

    def users_params
      params.require(:apply).permit(:user_id)
    end
end

app/controllers/gcals_controller.rb
class GcalsController < ApplicationController
  def create_event_self
    event = [
             current_user[:email],
             params[:title],
             params[:start],
             params[:end]
            ]
#UserのGmailが必要になるのでcurrent_user[:email]で渡す
    new_event = Gcal.new.insert_event(event)
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def new
    @job = Job.new
  end
end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController

  def index
    @recruitments = Recruitment.all.order("created_at DESC").each do
    end
  end

  def new
    @recruitment = Recruitment.new
  end

  def create
    @recruitment = Recruitment.create(title: recruitment_params[:title], text: recruitment_params[:text], image: recruitment_params[:image], campany_id: current_campany.id, campany_name: recruitment_params[:campany_name], job_type: recruitment_params[:job_type])

    redirect_to root_path
  end

  def show
    @recruitment = Recruitment.find(params[:id])
    if user_signed_in?
      @user = current_user.id
    elsif campany_signed_in?
      @campany = current_campany.id
    end
  end


  private

  def recruitment_params
    params.require(:recruitment).permit(:title, :text, :image, :id, :campany_name, :job_type)
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @recruitments = current_user.recruitments.order("created_at DESC").each do
    @applies = Apply.where(user_id: current_user.id)
    end
  end


private
  def user_params
    params.reqire(:user).permit(:user_id, :campany_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/recruitments/_campany_header.html.haml
.header
  .header__logo
    %a{:href => "/"}
      %img.icon{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
  .header__menu
    %ul
      %li
        %a{:href => "/recruitments/new"} 管理画面
      %li
        %a{:href => "/"} 募集一覧
      %li
        %a{:href => "/"} フィード
      %li
        %a{:href => "/"} ツール
      %li
        %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
          %span{:style => "position: relative; display: inline-block; direction: ltr;"}
            %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
          %i.wt-icon.wt-icon-search-short

  .header__profile
    %img.photo{:height => "40", :src => "/assets/icon.photo.jpg", :style => "display: block", :width => "40"}
    #modal-overlay
      .hidden-menu
        .hidden-menu__account
          %ul
            %li
              %a.account-link
                .name-area
                  .name-profile
                    / = current_campany.name
                  .name-edit プロフィール編集
        .hidden-menu__visit
          %ul
            %li
              %a.apply-visit{:href => "/campanies/show"} 応募求人
            %li
              %a.apply-visit{:href => "/"} 保存した募集
        .hidden-menu__user
          %ul
            %li
              %a.user-menu{:href => "/"} フォローしている会社
            %li
              %a.user-menu{:href => "/"}友達を招待
            %li
              %a.user-menu{:href => "/"}アカウント設定
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'user-menu'

app/views/recruitments/_home_header.html.haml
.menu-wrapper
.info-bar
  %p Wantedlyは、月間150万人が利用する国内最大級のビジネスSNSです
%header
  .header-logo
    %img.logo{:src => "/assets/wantedly.logo.png"}
  .header-form
    .field-input
    %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
  .field-right
    %ul
      %li
        %a#header-recruiter{:href => "/campanies/sign_in"} 採用担当者の方はこちら
      %li
        %a#header-signup.data-qtip.header-login-button.facebook{"aria-describedby" => "qtip-0", "data-hasqtip" => "0", "data-qtip-at" => "bottom center", "data-qtip-my" => "top right", "data-qtipv" => "Facebookのアカウントで登録・ログインしていただきます。Wantedlyが許可無くウォール等へ投稿することはありません。", :href => "https://www.wantedly.com/user/auth/facebook?ref=header_signup"}
      %li
        %a.log_in{:href => "/users/sign_in"} ログイン

app/views/recruitments/_recruitment.html.haml
- @recruitments.each do |recruitment|
  %img.job
    =image_tag recruitment.image
  .job-labels
    = recruitment.job_type
  %a.job-title{:href => "/recruitments/#{recruitment.id}"}
    = recruitment.title
  .job-introduction
    = recruitment.text
  .job-bottom
    %img.lazy{ :height => "50", :src => "/assets/logo.image.png", :style => "display: block;", :width => "50"}/
    .job-bottom__campany
      %a.campany-name
        = recruitment.campany_name
      %a.campany-prefecture 東京都

app/views/recruitments/_user_header.html.haml
.header
  .header__logo
    %a{:href => "/"}
      %img.icon{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
  .header__menu
    %ul
      %li
        %a{:href => "/"} 募集を見る
      %li
        %a{:href => "/"} フィード
      %li
        %a{:href => "/"} プロフィール
      %li
        %a{:href => "/"} ツール
      %li
        %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
          %span{:style => "position: relative; display: inline-block; direction: ltr;"}
            %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
          %i.wt-icon.wt-icon-search-short
  %a.calendar-btn 面接予定

  .header__profile
    %img.photo{:height => "40", :src => "/assets/icon.photo.jpg", :style => "display: block", :width => "40"}
    #modal-overlay
      .hidden-menu
        .hidden-menu__account
          %ul
            %li
              %a.account-link
                .name-area
                  .name-profile
                    = current_user.user_name
                  .name-edit プロフィール編集
        .hidden-menu__visit
          %ul
            %li
              %a.apply-visit{:href => "/users/#{current_user.id}"} 応募した企業
            %li
              %a.apply-visit{:href => "/"} 保存した募集
        .hidden-menu__user
          %ul
            %li
              %a.user-menu{:href => "/"} フォローしている会社
            %li
              %a.user-menu{:href => "/"}友達を招待
            %li
              %a.user-menu{:href => "/"}アカウント設定
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'user-menu'

app/views/recruitments/index.html.haml
#modal-content
  #calendar
    %a.menu-btn 閉じる





- if campany_signed_in?
  = render '/recruitments/campany_header'
- elsif user_signed_in?
  = render '/recruitments/user_header'
- else
  = render '/recruitments/home_header'



.main-contents
  .main-contents__company
    =image_tag "CompanyOverview.png"
    .main-contents__details
      .main-contents__details__job
        エンジニア
      %h2.main-contents__details__title ワクワクするような企業を一番近くでサポートして、もっと成長させてくれる人
      %p.main-contents__details__name
        %img.logo{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
        %a{:href => "/"} 株式会社リクルートスタッフ
  .main-contents__company
    =image_tag "job.image1.png"
    .main-contents__details
      .main-contents__details__job
        エンジニア
      %h2.main-contents__details__title ユーザビリティに徹底的にこだわるフロントエンジニアを募集！
      %p.main-contents__details__name
        %img.logo{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
        %a{:href => "/"} 株式会社 高久田
  .main-contents__company
    =image_tag "job.image3.jpeg"
    .main-contents__details
      .main-contents__details__job
        エンジニア
      %h2.main-contents__details__title 未経験OK！！ITであなたの「夢」を叶えたいWebエンジニア募集！
      %p.main-contents__details__name
        %img.logo{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
        %a{:href => "/"} 株式会社ASCOM

.recruitment-contents
  .recruitment-contents__center
    .recruitment-contents__center__left
      .recruitment-contents__center__left__inner
        .recruitment-contents__center__left__inner__menu
          .menu-header
            %h4 検索条件
          .menu-contents
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "エンジニア", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "中途採用", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-form
              %input#search{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "地域や特徴などの条件を追加", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
            .job-word
              %ul
                %li ゲーム
                %li IoT
                %li 人工知能
                %li 英語
                %li フルスタック
            .job-style
              %h5 分野
              %ul
                %li web エンジニア
                %li モバイルエンジニア
                %li インフラエンジニア
            .job-style
              %h5 地域
              %ul
                %li 北海道・東北
                %li 中国・四国
                %li 関東
            .job-style
              %h5 特徴
              %ul
                %li TechCrunchに掲載実績あり
                %li 1億円以上の資金を調達済み
                %li Skypeで話を聞ける

    .recruitment-contents__center__main
      .recruitment-contents__center__main-menu
        %p.recruitment-count 10/16169
        %ul
          %li
            %a おすすめ
          %li
            %a 新着
          %li
            %a 人気
        .h4 並び替え
        .recruitment-contents__center__main-area
          .recruitment-contents__center__main-area-messages
            = render @recruitments

%footer.index-footer
  .footer-inner
    .footer-inner__main
      .footer-logo
        %img.logo{:src => "/assets/wantedly.logo.png"}

app/views/recruitments/new.html.haml
.header
  .header__logo
    %a{:href => "/"}
      %img.icon{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
  .header__menu
    %ul
      %li
        %a{:href => "/"} 管理画面
      %li
        %a{:href => "/"} 募集一覧
      %li
        %a{:href => "/"} フィード
      %li
        %a{:href => "/"} ツール
      %li
        %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
          %span{:style => "position: relative; display: inline-block; direction: ltr;"}
            %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
          %i.wt-icon.wt-icon-search-short
  .header__profile
    %img.photo{:height => "40", :src => "/assets/icon.photo.jpg", :style => "display: block", :width => "40"}
= form_for @recruitment do |f|

  .recruitment-main
    .recruitment-main__bar
      .recruitment-main__bar__inner
        .recruitment-main__bar__inner__section
          %li.item 新規募集作成
          %a{:href => "/"}
          %li.item ダッシュボード
          .punctuation 管理
          %li.item 募集
          %li.item フィード
          %li.item アナリティクス
          .punctuation 候補者
          %li.item 候補者
          %li.item メッセージ
    .recruitment-main__right
      .recruitment-main__right__contents
        .recruitment-main__right__contents__header
          %ul#tabs
            %li.step1 STEP1 会社情報の入力
            %li.step2 STEP2 社員の追加
            %li.step3 STEP3 募集の作成
        .recruitment-main__right__contents__message
          %i.icon-heart{:style => "color: pink; line-height: 1.2;"}
            %h2.center-massage 求人ではなく、ラブレターを書くつもりで
            %p 大事なのは、「会いにいきたい」と思って貰えることです。
            %p 飾らずに、自分の言葉で、まっすぐに自分たちの熱い思いを書き綴りましょう。
            %p.bottom-message 理想的な募集要項を作成していただくため、コンテンツ・クオリティ・ガイドラインを設けております。必ずご一読下さい。
        .recruitment-main__right__contents__name
          .recruitment-main__right__contents__name__form
            .field-label
              = f.label "会社の名前は？"
            .field-name
              = f.text_field :campany_name, placeholder: :会社名を入力してください
        .recruitment-main__right__contents__job
          .recruitment-main__right__contents__job__form
            .field-label
              = f.label "募集する職種は？"
            .field-select
              = f.text_field :job_type, placeholder: :職種を入力してください
        .recruitment-main__right__contents__title
          .recruitment-main__right__contents__title__form
            .field-label
              = f.label "タイトルを入力する"
              %abbr (必須)
            .field-text
              = f.text_field :title, placeholder: :ユーザー6万人の人材サイトに喝を入れるwebデザイナー募集
        .recruitment-main__right__contents__detail
          .recruitment-main__right__contents__detail__form
            .field-label
              = f.label "募集の詳細を入力する"
              %abbr (必須)
            .field-detail
              = f.text_field :text, placeholder: :募集要項の詳細を入力して下さい
        .recruitment-main__right__contents__image
          .recruitment-main__right__contents__image__form
            .field-label
              = f.label "会社イメージ"
              %abbr (任意)
            .field-image
              = f.file_field :image
        .recruitment-main__right__contents__teach
          %i.icon-user
          %h2.center-message あなたの会社に必要な人は、どんな人ですか？
          %p これが最後の入力項目です。
          %p どんな相手に「ラブレター」を送るのか相手を思い浮かべながら書いてみましょう。
        .recruitment-main__right__contents__what
          .recruitment-main__right__contents__what__form
            .field-label
              = f.label "何をやっているのか"



        .recruitment-main__right__contents__bottom
          = link_to "戻る", root_path, class: "return-btn"
          = f.submit "投稿する", class: "send-btn"

app/views/recruitments/show.html.haml
.header
  .header__logo
    %a{:href => "/"}
      %img.icon{:alt => "Wantedly", :height => "44px", :src => "https://de7iszmjjjuya.cloudfront.net/assets/wantedly-logo-5906d9a368d0bcdd2919553127357d4d.svg", :width => "44px", :margin => "0"}/
  .header__menu
    %ul
      %li
        %a{:href => "/"} 募集を見る
      %li
        %a{:href => "/"} フィード
      %li
        %a{:href => "/"} プロフィール
      %li
        %a{:href => "/"} ツール
      %li
        %form.search{"accept-charset" => "UTF-8", :action => "/search", :method => "get"}
          %span{:style => "position: relative; display: inline-block; direction: ltr;"}
            %input.input{:autocomplete => "off", :dir => "auto", :name => "q", :placeholder => "人や会社、募集を検索", :spellcheck => "false", :style => "position: relative; vertical-align: top;", :type => "text"}/
          %i.wt-icon.wt-icon-search-short

  .header__profile
    %img.photo{:height => "40", :src => "/assets/icon.photo.jpg", :style => "display: block", :width => "40"}
    #modal-overlay
      .hidden-menu
        .hidden-menu__account
          %ul
            %li
              %a.account-link
                .name-area
                  .name-profile
                    / = current_campany.name
                  .name-edit プロフィール編集
        .hidden-menu__visit
          %ul
            %li
              %a.apply-visit{:href => "/campanies/show"} 応募求人
            %li
              %a.apply-visit{:href => "/"} 保存した募集
        .hidden-menu__user
          %ul
            %li
              %a.user-menu{:href => "/"} フォローしている会社
            %li
              %a.user-menu{:href => "/"}友達を招待
            %li
              %a.user-menu{:href => "/"}アカウント設定
            %li
              = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'user-menu'



.detail-contents
  .detail-contents__main
    .detail-contents__main__header
      .detail-contents__main__header__title
        .detail-contents__main__header__title__icon
        %h1.title
          = @recruitment.title
        .detail-contents__main__header__title__name
          .detail-contents__main__header__title__name__icon
          %a.campany-name
            = @recruitment.campany_name
      .detail-contents__main__header__image
        .detail-contents__main__header__image__main
          = image_tag @recruitment.image
        %ul.bottom-menu
          %li.time 2017/06/10
          %li.friends 社員とあなたの共通の友達
          %li.total-view 3577
          %li.btn
    .detail-contents__main__area
      .detail-contents__main__area__inner
    .detail-contents__main__side
      .detail-contents__main__side__btn
        .detail-contents__main__side__btn__inner
          - if current_user
            .apply-btn
              = link_to "話を聞きにいきたい", recruitment_applies_path(@recruitment), method: :post, class:'btn'